// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace LoadDwOrders.Models.Models;

public partial class NorwindContext : DbContext
{
    public NorwindContext(DbContextOptions<NorwindContext> options)
        : base(options)
    {
    }

    public virtual DbSet<VwFactCustomersAtended> VwFactCustomersAtendeds { get; set; }

    public virtual DbSet<VwFactSale> VwFactSales { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<VwFactCustomersAtended>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("vw_FactCustomersAtended", "DWH");

            entity.Property(e => e.EmployeeId).HasColumnName("EmployeeID");
            entity.Property(e => e.EmployeeName)
                .IsRequired()
                .HasMaxLength(31);
        });

        modelBuilder.Entity<VwFactSale>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("vwFactSales", "DWH");

            entity.Property(e => e.City).HasMaxLength(15);
            entity.Property(e => e.CompanyName)
                .IsRequired()
                .HasMaxLength(40);
            entity.Property(e => e.CustomerId)
                .IsRequired()
                .HasMaxLength(5)
                .IsFixedLength()
                .HasColumnName("CustomerID");
            entity.Property(e => e.EmployeeId).HasColumnName("EmployeeID");
            entity.Property(e => e.EmployeeName)
                .IsRequired()
                .HasMaxLength(31);
            entity.Property(e => e.ProductId).HasColumnName("ProductID");
            entity.Property(e => e.ProductName)
                .IsRequired()
                .HasMaxLength(40);
            entity.Property(e => e.ShipperId).HasColumnName("ShipperID");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}