// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LoadDwOrders.Models.Models;

public partial class VwFactCustomersAtended
{
    public int? EmployeeId { get; set; }

    public string EmployeeName { get; set; }

    public int? TotalCustomerServed { get; set; }
}