// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LoadDwOrders.Models.Models;

public partial class VwFactSale
{
    public string CustomerId { get; set; }

    public string EmployeeName { get; set; }

    public int? EmployeeId { get; set; }

    public int? ShipperId { get; set; }

    public string CompanyName { get; set; }

    public string City { get; set; }

    public int ProductId { get; set; }

    public int? Año { get; set; }

    public int? Mes { get; set; }

    public double? TotalVentas { get; set; }

    public int? Cantidad { get; set; }

    public string ProductName { get; set; }
}