// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace LoadDwOrders.Models.DWOrders.ModelsOrders;

public partial class DWHNorthwindOrdersContext : DbContext
{
    public DWHNorthwindOrdersContext(DbContextOptions<DWHNorthwindOrdersContext> options)
        : base(options)
    {
    }

    public virtual DbSet<FactCustomersAttended> FactCustomersAttendeds { get; set; }

    public virtual DbSet<FactSale> FactSales { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<FactCustomersAttended>(entity =>
        {
            entity.HasKey(e => e.AttendedKey).HasName("PK__FactCust__A28BAACDD161F623");

            entity.ToTable("FactCustomersAttended");

            entity.HasIndex(e => e.CustomerKey, "idx_fact_customers_attended_customer");

            entity.HasIndex(e => e.EmployeeKey, "idx_fact_customers_attended_employee");

            entity.HasIndex(e => e.ProductKey, "idx_fact_customers_attended_product");

            entity.HasIndex(e => e.TimeKey, "idx_fact_customers_attended_time");
        });

        modelBuilder.Entity<FactSale>(entity =>
        {
            entity.HasKey(e => e.SaleKey).HasName("PK__FactSale__1C32977D045AD2EE");

            entity.HasIndex(e => e.CategoryKey, "idx_fact_sales_category");

            entity.HasIndex(e => e.CustomerKey, "idx_fact_sales_customer");

            entity.HasIndex(e => e.EmployeeKey, "idx_fact_sales_employee");

            entity.HasIndex(e => e.ProductKey, "idx_fact_sales_product");

            entity.HasIndex(e => e.ShipperKey, "idx_fact_sales_shipper");

            entity.HasIndex(e => e.TimeKey, "idx_fact_sales_time");

            entity.Property(e => e.City).HasMaxLength(100);
            entity.Property(e => e.EmployeeName)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.ProductName)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.TotalVentas).HasColumnType("decimal(18, 2)");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}