// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LoadDwOrders.Models.DWOrders.ModelsOrders;

public partial class FactCustomersAttended
{
    public int AttendedKey { get; set; }

    public int? TimeKey { get; set; }

    public int? CustomerKey { get; set; }

    public int? EmployeeKey { get; set; }

    public int? ProductKey { get; set; }

    public int? TotalCustomersServed { get; set; }
}