// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LoadDwOrders.Models.DWOrders.ModelsOrders;

public partial class FactSale
{
    public int SaleKey { get; set; }

    public int? TimeKey { get; set; }

    public int? CustomerKey { get; set; }

    public int? EmployeeKey { get; set; }

    public int? ProductKey { get; set; }

    public int? ShipperKey { get; set; }

    public int? CategoryKey { get; set; }

    public int? CantidadVentas { get; set; }

    public decimal? TotalVentas { get; set; }

    public string ProductName { get; set; }

    public string EmployeeName { get; set; }

    public string City { get; set; }
}